### ISSUE TITLE
the LLAMA model doesn't seem to remember the previous questions

### ISSUE THREAD

**Issue by josura** [FCL-LM/privateGPT#9]
The model doesn't seem to remember previous questions and answers

**Comment by josura** [comment]
The Q&A Chain model doesn't take into account the previous answers, so we need to change the chain model itself if possible

**Comment by nebuchadneZZar01** [comment]
Should be working with commit https://github.com/FCL-LM/privateGPT/commit/353e5a81a8658bc633cd3d0104caec622b6907ca, using the Q&A chain with a Retrivial Chain with Buffered Memory

**Comment by josura** [comment]
Problem "resolved" 353e5a8 , even though we need to understand the use case of the users, closing the issue for now.

**Comment by josura** [comment]
To add a prompt if needed https://stackoverflow.com/questions/76175046/how-to-add-prompt-to-langchain-conversationalretrievalchain-chat-over-docs-with
